main/urls.py
from django.urls import path
from .views import *

app_name= "main"

urlpatterns = [
    path('', main, name="showmain"),
    path('showfirst/', showfirst, name="showfirst"),
    # firstpage URL 연결하기 with 별명사용
    path('showsecond/', showsecond, name="showsecond"),
    path('posts/', posts, name="posts"),
    path('<int:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<str:id>', delete, name="delete"),
]

project3/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    id= models.AutoField(primary_key=True)
    title= models.CharField(max_length=200)
    writer=models.CharField(max_length=100)
    pub_date=models.DateTimeField()
    body=models.TextField()
    image= models.ImageField(upload_to = "blog/", blank=True, null = True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]

main/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Post
from django.utils import timezone
# Create your views here.

# mainpage view 함수
def main(request):
    return render(request, 'main/mainpage.html')
######showmain->posts####
def posts(request):
    posts= Post.objects.all()
    return render(request, 'main/mainpage.html',{'posts': posts})

# firstpage view 함수
def showfirst(request):
    return render(request, 'main/firstpage.html')

# secondpage view 함수
def showsecond(request):
    return render(request, 'main/secondpage.html')
def detail(request, id):
    post=get_object_or_404(Post, pk= id)
    return render(request, 'main/detail.html',{'post':post})

def new(request):
    return render(request, 'main/new.html')   
#데이터베이스에 데이터를 저장하는 create 함수
def create(request):
    new_post = Post()
    new_post.title=request.POST['title']
    new_post.writer=request.POST['writer']
    new_post.pub_date=timezone.now()
    new_post.body=request.POST['body']
    new_post.image=request.FILES.get('image')
    new_post.save()
    return redirect('main:detail',new_post.id)

def edit(request, id):
    edit_post= Post.objects.get(id=id)
    return render(request, 'main/edit.html',{'post' : edit_post})

def update(request, id):
    update_post = Post.objects.get(id=id)
    update_post.tilte= request.POST['title']
    update_post.writer= request.POST['writer']
    update_post.pub_date = timezone.now()
    update_post.body = request.POST['body']
    update_post.image=request.FILES.get('image')
    update_post.save()
    return redirect('main:detail', update_post.id)
    
def delete(request, id):
    delete_post =Post.objects.get(id=id)
    delete_post.delete()
    return redirect('main:posts') 

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}  

{% block content %}  

<h1>{{post.title}}</h1>
작성자: {{post.writer}}
날짜: {{post.pub_date}}
<hr>
{% if post.image %}
    <p><img src="{{ post.image.url }}" alt="사진"></p>
{% endif %}
<p>{{post.body}}</p>
<a href="{%url 'main:edit' post.id%}">수정하기</a>
<a href="{%url 'main:delete' post.id%}">삭제하기</a>
{% endblock%} 

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}  

{% block content %} 
<div class="container">
    <h1>글 수정하기</h1>
    <form action= "{% url 'main:update' post.id %}" method ="post">
        {%csrf_token%}  
        <p>제목: <input type="text" name="title" value="{{post.title}}"></p>
        <p>작성자: <input type="text" name="writer" value="{{post.writer}}"></p>
        <p>사진: <input type = "file" name="image" value="{{post.image}}"></p>
        <p>내용: <textarea type="text" name="body" id="" cols="30" rows="10" >{{post.body}}</textarea></p>
        <button type="submit">제출</button> 
    </form>
</div>      

{% endblock%} 

main/templates/main/firstpage.html
<h1>firstpage 입니다.</h1>

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    <div class="mainbox">
        <h1>안녕하세요!</h1>
        <h1>서연미입니다.</h1>
        </div>

        <p class="category">ABOUT ME</p>  
        <ul class="aboutme">
            <li>나이: 23살</li>
            <li>전공: 경영학과</li>
            <li>MBTI: ESFP</li>
        </ul>

        <p class="category">LIKE</p>
        <ul class="like">
            
            <li>취미</li>
            <ol class= "content">
                <li>필름사진 찍기</li>
                <li>넷플릭스 구경하기</li>
            </ol>

            <li>좋아하는 음식</li>
                <p class= "content">  아이스크림</p>
                <p class= "content">  엽떡</p>
            
            <li>좋아하는 공간</li>
                <p class= "content">노들섬</p>
                <p class= "content">우도</p>
    

            
            
            

        </ul>
    <img src="{% static 'images/hi.jpg' %}">
    <!-- firstpage 링크 연결 -->
    <a href="{% url 'main:showfirst'%}">First page</a>
    <!-- secondpage 링크 연결-->
    <a href="{% url 'main:showsecond'%}">Second page</a>
    
<h2><a href="{% url 'main:new'%}">글쓰기</a></h2>

<h1>글 목록</h1>

<div>
{%for post in posts %}
<div>
    <h3>{{post.title}}</h3>
    {{post.writer}}<br>
    {{post.summary}}
<a href="{% url 'main:detail' post.id %}">...자세히</a>
    <br>
</div>
{% endfor%}

</div>
{% endblock %}  

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}  

{% block content %} 

<form action="{% url 'main:create'%}" method ="post" enctype="multipart/form-data">
    {%csrf_token%}  
    <p>제목: <input type="text" name="title"></p>
    <p>작성자: <input type="text" name="writer"></p>
    <p>사진: <input type = "file" name="image"></p>
    <p>내용: <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button> 
</form>       

{% endblock%} 

main/templates/main/secondpage.html
<h1>secondpage 입니다.</h1>

project3/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>2022 Likelion Dongguk</title>
    <!--CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <!--JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!--우리가 직접 구현한 css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}"> 

</head>
<body>
    {% include 'shared/_navbar.html' %}
    <div calss="container">
        {% block content %}

        {% endblock %}
    </div>
</body>        

</html>

project3/templates/shared/_navbar.html
   <!--navbar-->
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>